// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsm_Kfy0YE7NrvHanEZ4i9fC1maib45As',
    appId: '1:247246484945:android:9816ab5f9f1d102a279cf0',
    messagingSenderId: '247246484945',
    projectId: 'brightspeak-e95eb',
    databaseURL: 'https://brightspeak-e95eb-default-rtdb.firebaseio.com',
    storageBucket: 'brightspeak-e95eb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQLTpz7WkTotuxGlVxDMFP8ezs8zCHOEc',
    appId: '1:247246484945:web:da047045ca137b86279cf0',
    messagingSenderId: '247246484945',
    projectId: 'brightspeak-e95eb',
    authDomain: 'brightspeak-e95eb.firebaseapp.com',
    databaseURL: 'https://brightspeak-e95eb-default-rtdb.firebaseio.com',
    storageBucket: 'brightspeak-e95eb.firebasestorage.app',
    measurementId: 'G-TM1BBCWGDN',
  );

}